# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-swf?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: swf
    password: swf1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
server:
  port: 9000

# Activiti7配置
activiti:
  check-process-definitions: false # 关闭自动部署
  # database-schema-update: true
  # history-level: full
  # db-history-used: true
